apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: deepseek-model-config
  namespace: kagent
spec:
  model: deepseek-chat
  provider: OpenAI
  apiKeySecret: kagent-deepseek
  apiKeySecretKey: DEEPSEEK_API_KEY
  openAI:
    baseUrl: "https://api.deepseek.com/v1"
